### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by kevinchugh** [shubhmsng/blurred-barcode-extraction#2]
Hi, do you mind giving a command line recipe to try this?  Also any installation instructions would be great.  We are looking for barcode image deblurring and this looks promising. Thanks for any help.
Kevin

**Comment by shubhmsng** [comment]
`pythton3 project.py`
Use the above command to run this application. There are some library dependencies that are mentioned in Readme file. you need those libraries to be installed that's it.
